### ISSUE TITLE
Checking that authz entitlements and permissions do exist

### ISSUE THREAD

**Issue by mrded** [snyk/sweater-comb#243]
`x-cerberus` extension allows setting required entitlements and permissions checks. We need to make sure that those entitlements and permissions do exist.

Example:
```
x-cerberus:
  authorization:
    skip: false
    context:
      resourceIdParam: 'orgId'
      resourceType: 'org'
    entitlements:
      - entitlement0
      - entitlement1
    permissions:
      - read
      - test
```

Provided entitlements and permissions must be defined here: https://snyk.roadie.so/catalog/default/api/authz
