### ISSUE TITLE
properties of allOf must not overlap

### ISSUE THREAD

**Issue by mrded** [snyk/sweater-comb#252]
Consider example:
```
    allOf: 
        - type: object
          properties:
            foo:
              type: string
            bar:
              type: string
        - type: object
          properties:
            foo:
              type: boolean
```

This should not be possible as `foo string` is overlapping with `foo bool`.

[Slack disscussion](https://snyk.slack.com/archives/C01JD0DKS3D/p1651160687888879)
