### ISSUE TITLE
[JSON API] Relationships must exist

### ISSUE THREAD

**Issue by cmars** [snyk/sweater-comb#333]
A path like `/orgs/{org_id}/relationships/authorized_apps` means that when requesting `/orgs/{org_id}`, that resource provides a relationship,

```
  relationships:
    authorized_apps:
      links:
        related: /path/to/authorized_apps
```

If it doesn't, then the relationship path is invalid.

We need a rule that can check for this and flag broken relationships in our API.
