### ISSUE TITLE
Resource Identifiers cannot contain non alpha characters, such as `_`

### ISSUE THREAD

**Issue by mikedevelops** [snyk/sweater-comb#485]
We ran into some issues recently where our specs would fail linting due to this regex in sweater-comb: https://github.com/snyk/sweater-comb/blob/a64b1e9f9602baa550af4fd18fc1be54b3f87a87/src/rulesets/rest/2022-05-25/utils.ts#L15

It looks as though sweater-comb was unable to determine that the endpoint was a get-one operation due to the naming convention of the resource identifier.

Example:

```
orgs/{org_id}/service_accounts/{service_account_id}:  
   get:
      summary: Get an organization service account.
         ...
      parameters:
        - name: org_id
         ...
        - name: service_account_id
          in: path
          required: true
          description: The ID of the service account.
          schema:
            type: string
            format: uuid
```

```
   FAIL  GET /orgs/{org_id}/service_accounts/{service_account_id}
    added rule [error]: pagination parameters
      x Could not find a partial match in query parameters
```

We were able to work around it by conforming to the regex and using `serviceacount_id`. Perhaps this is fine and just needs documenting, otherwise, it might be nice to tweak the regex to allow for more readable resource identifiers.
